export const DATETIME_FORMAT = {
  // API REQUEST / RESPONSE
  API_DATE: 'YYYY-MM-DD',
  API_TIME: 'HH:mm:ss',
  API_DATETIME: 'YYYY-MM-DD HH:mm:ss',
  DISPLAY_DATETIME: 'll(dddd)',
  DISPLAY_DATETIME_AND_DAY: 'll(dd)',
  LOCALE_DATE: 'll',
  LOCALE_DATE_WITH_TIME: 'll HH:mm',
  VIEW_DATE: 'Y/m/d',
  VIEW_DATE_CROSS: 'Y-m-d',
  VIEW_DATE_TIME_JP: 'YYYY年MM月DD日 HH:mm',
  VIEW_FULL_DATE: 'YYYY/MM/DD',
  VIEW_DATE_TIME_CUSTOM: 'YYYY/MM/DD HH:mm',
  VIEW_DATE_TIME_MESSAGE: 'YYYY.MM.DD HH:mm',
  VIEW_HOUR_MINUTE: 'HH:mm'
}
